{{cookiecutter.project_slug}}/app/users/urls.py
from django.urls import path

from . import views


app_name = 'users'
urlpatterns = [
    path('update/profile/', view=views.settings_profile, name='settings_profile'),
    path('update/social/', view=views.settings_social, name='settings_social'),
    path('update/password/', view=views.settings_password, name='settings_password'),

    path('<int:user_id>/', views.public_profile, name='profile'),
]

{{cookiecutter.project_slug}}/config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.views import defaults as default_views
from django.urls import path


urlpatterns = [
    # Django Admin
    path('admin/', admin.site.urls),

    # User Account
    path('accounts/', include('app.accounts.urls')),
    path('users/', include('app.users.urls', namespace='users')),

    # Pages
    path('', include('app.pages.urls', namespace='pages')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path('400/', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        path('403/', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        path('404/', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        path('500/', default_views.server_error),
    ]

    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [path('__debug__/', include(debug_toolbar.urls)),] + urlpatterns

{{cookiecutter.project_slug}}/app/pages/templates/pages/homepage.html
{% raw %}{% extends "base.html" %}
{% block body_css_class %}page-homepage{% endblock %}

{% block body_content %}
  <div class="container-fluid">
    <header>
      <h1>Welcome to {% endraw %}{{cookiecutter.project_name}}{% raw %}</h1>
      <p>You can start using this boilerplate by creating a new app using Django's startapp command</p>
      <pre>$ startapp [app_label] ./app/</pre>
    </header>

    <div class="account">
      <hr/>
      {% if not user.is_authenticated %}
        <p>You're currently not logged in.</p>
        <div class="actions">
          <a href="{% url 'account_login' %}" class="btn btn-light">Login</a> <a href="{% url 'account_signup' %}" class="btn btn-primary">Sign up</a>
        </div>
      {% else %}
        <p>Logged in as :
          <a href="{% url 'users:profile' user.id %}">{{ user.display_name }}</a>
          &lt;{{ user.email }}&gt; | <a href="{% url 'users:settings_profile' %}">Account settings</a> | <a href="{% url 'account_logout' %}">Logout</a>
        </p>
      {% endif %}
    </div>
  </div>
{% endblock %}
{% endraw %}